baseurl: https://www.christianvillanueva.com/
languageCode: en-us
theme: hugo-theme-terminal
paginate: 5
params:
  centerTheme: no
  contentTypeName: posts
  fullWidthTheme: no
  showMenuItems: 3
  themeColor: orange
languages:
  en:
    copyright: ''
    keywords: ''
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: showcase
          name: Showcase
          url: /showcase
        - identifier: experience
          name: Experience
          url: /experience
   # menuMore: Show more
    params:
      logo:
        logoHomeLink: /
        logoText: home
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: A simple, retro theme for Hugo
    title: Terminal
